name: Internet Speed Test

on:
  workflow_dispatch:

jobs:
  run-speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Install Speedtest CLI
        run: |
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
          sudo apt-get install -y speedtest

      - name: Run Speedtest and Save Result
        run: speedtest --accept-license --accept-gdpr > speedtest-result.txt

      - name: Upload Speedtest Result
        uses: actions/upload-artifact@v4
        with:
          name: speedtest-report
          path: speedtest-result.txt
