name: Internet Speed Test

on:
  workflow_dispatch:

jobs:
  run-speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Install Speedtest CLI
        run: |
          # Скачиваем архив с официального сайта
          curl -Lo speedtest.tgz https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
          # Распаковываем его
          tar -xzf speedtest.tgz

      - name: Run Speedtest and Save Result
        # Запускаем бинарник из текущей папки и принимаем лицензию
        run: ./speedtest --accept-license --accept-gdpr > speedtest-result.txt

      - name: Upload Speedtest Result
        uses: actions/upload-artifact@v4
        with:
          name: speedtest-report
          path: speedtest-result.txt
